"""
Application constants for STPA Tool
Defines application-wide constants and default values.
"""

import os
from pathlib import Path

# Application Information
APP_NAME = "STPA Tool"
APP_VERSION = "1.0.0"
APP_AUTHOR = "Nicholas Triska"
APP_DESCRIPTION = "Systems-Theoretic Process Analysis Tool"

# Database Configuration
DEFAULT_DB_NAME = "stpa.db"
DB_TIMEOUT = 30.0  # seconds
DB_WAL_MODE = True

# Configuration Files
CONFIG_FILE_JSON = "config.json"
CONFIG_FILE_YAML = "config.yaml"

# Directory Structure
DIAGRAMS_DIR = "diagrams"
BASELINES_DIR = "baselines"
TEMP_DIR = "temp"

# File Extensions
DB_EXTENSION = ".db"
JSON_EXTENSION = ".json"
YAML_EXTENSION = ".yaml"
MERMAID_EXTENSION = ".mmd"
SVG_EXTENSION = ".svg"
PNG_EXTENSION = ".png"
MD_EXTENSION = ".md"

# Entity Type Identifiers
SYSTEM_TYPE = "S"
FUNCTION_TYPE = "F"
INTERFACE_TYPE = "I"
ASSET_TYPE = "A"
CONSTRAINT_TYPE = "C"
REQUIREMENT_TYPE = "R"
ENVIRONMENT_TYPE = "E"
HAZARD_TYPE = "H"
LOSS_TYPE = "L"
CONTROL_STRUCTURE_TYPE = "CS"
CONTROLLER_TYPE = "CT"
CONTROLLED_PROCESS_TYPE = "CP"
CONTROL_ACTION_TYPE = "CA"
FEEDBACK_TYPE = "FB"
CONTROL_ALGORITHM_TYPE = "CAL"
PROCESS_MODEL_TYPE = "PM"
STATE_DIAGRAM_TYPE = "SD"
STATE_TYPE = "ST"
IN_TRANSITION_TYPE = "IT"
OUT_TRANSITION_TYPE = "OT"
SAFETY_SECURITY_CONTROL_TYPE = "SC"

# Criticality Levels
CRITICALITY_NON_CRITICAL = "Non-Critical"
CRITICALITY_MISSION_CRITICAL = "Mission Critical"
CRITICALITY_SAFETY_CRITICAL = "Safety Critical"
CRITICALITY_FLIGHT_CRITICAL = "Flight Critical"
CRITICALITY_SECURITY_CRITICAL = "Security Critical"
CRITICALITY_PRIVACY_CRITICAL = "Privacy Critical"

CRITICALITY_LEVELS = [
    CRITICALITY_NON_CRITICAL,
    CRITICALITY_MISSION_CRITICAL,
    CRITICALITY_SAFETY_CRITICAL,
    CRITICALITY_FLIGHT_CRITICAL,
    CRITICALITY_SECURITY_CRITICAL,
    CRITICALITY_PRIVACY_CRITICAL
]

# Verification Methods
VERIFICATION_INSPECTION = "Inspection"
VERIFICATION_ANALYSIS = "Analysis"
VERIFICATION_DEMONSTRATION = "Demonstration"
VERIFICATION_TEST = "Test"

VERIFICATION_METHODS = [
    VERIFICATION_INSPECTION,
    VERIFICATION_ANALYSIS,
    VERIFICATION_DEMONSTRATION,
    VERIFICATION_TEST
]

# Imperatives
IMPERATIVE_SHALL = "Shall"
IMPERATIVE_SHOULD = "Should"
IMPERATIVE_MAY = "May"
IMPERATIVE_WILL = "Will"

IMPERATIVES = [
    IMPERATIVE_SHALL,
    IMPERATIVE_SHOULD,
    IMPERATIVE_MAY,
    IMPERATIVE_WILL
]

# Baseline Constants
WORKING_BASELINE = "Working"
BASELINE_DATE_FORMAT = "%Y-%m-%d"

# UI Constants
WINDOW_MIN_WIDTH = 1024
WINDOW_MIN_HEIGHT = 768
SPLITTER_DEFAULT_SIZES = [300, 700]

# Performance Limits
MAX_RECORDS_THRESHOLD = 100000
THUMBNAIL_LAZY_LOAD_THRESHOLD = 200

# Hash Algorithm
HASH_ALGORITHM = "sha256"

# Default Text Field Lengths
SHORT_TEXT_LENGTH = 256
LONG_TEXT_LENGTH = 4000

# File Permissions (Unix-style)
DEFAULT_FILE_PERMISSIONS = 0o644
DEFAULT_DIR_PERMISSIONS = 0o755